[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.1.0"
  NODE_VERSION = "18"
  BUNDLE_CACHE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200